---
fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "8.2.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "8.3.0"
    unattended_upgrades:
      repo: "puppet/unattended_upgrades"
      ref: "6.0.0"
    systemd:
      repo: "puppet/systemd"
      ref: "3.8.0"
    chrony:
      repo: "puppet/chrony"
      ref: "2.4.0"
    sshkeys_core:
      repo: "puppetlabs/sshkeys_core"
      ref: "2.3.0"
    nginx:
      repo: "puppet/nginx"
      ref: "3.3.0"
    letsencrypt:
      repo: "puppet/letsencrypt"
      ref: "8.0.2"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "5.3.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "7.2.0"
